# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='role',
            new_name='roles',
        ),
    ]
